#!/bin/bash

# Cloud Ninja Solutions - Custom Domain Setup for GitHub Pages
# This script helps you set up a custom domain (FREE hosting on GitHub Pages)

echo "🌐 Custom Domain Setup for Cloud Ninja Solutions"
echo "==============================================="

echo ""
echo "✅ YES! You can use a custom domain with GitHub Pages for FREE!"
echo ""
echo "💰 COST BREAKDOWN:"
echo "   Domain registration: ~$10-15/year (one-time cost)"
echo "   GitHub Pages hosting: FREE forever"
echo "   SSL certificate: FREE (auto-generated)"
echo "   CDN: FREE (global edge locations)"
echo ""

echo "🎯 RECOMMENDED DOMAINS:"
echo "   • cloudninjasolutions.com"
echo "   • cloudninja.dev"
echo "   • gabrieletupini.dev"
echo "   • tupinidevops.com"
echo ""

echo "🛒 WHERE TO BUY:"
echo "   • Namecheap.com (recommended)"
echo "   • GoDaddy.com"
echo "   • Google Domains"
echo "   • Cloudflare Domains"
echo ""

echo "⚙️  SETUP STEPS (After buying domain):"
echo ""
echo "1️⃣  CREATE CNAME FILE:"
echo "   Create file: CNAME (no extension)"
echo "   Content: yourdomain.com"
echo "   Example: echo 'cloudninjasolutions.com' > CNAME"
echo ""

echo "2️⃣  CONFIGURE DNS (at your domain provider):"
echo "   Add these DNS records:"
echo ""
echo "   📌 For ROOT domain (cloudninjasolutions.com):"
echo "      Type: A"
echo "      Name: @"
echo "      Value: 185.199.108.153"
echo ""
echo "   📌 For ROOT domain (alternate records):"
echo "      Type: A, Name: @, Value: 185.199.109.153"
echo "      Type: A, Name: @, Value: 185.199.110.153" 
echo "      Type: A, Name: @, Value: 185.199.111.153"
echo ""
echo "   📌 For WWW subdomain:"
echo "      Type: CNAME"
echo "      Name: www"
echo "      Value: yourgithubusername.github.io"
echo ""

echo "3️⃣  ENABLE IN GITHUB:"
echo "   • Go to repo Settings → Pages"
echo "   • Under 'Custom domain' enter: yourdomain.com"
echo "   • Check 'Enforce HTTPS'"
echo "   • Save"
echo ""

echo "🕐 TIMING:"
echo "   • DNS changes: 5-60 minutes"
echo "   • SSL certificate: 5-10 minutes after DNS"
echo "   • Full propagation: up to 24 hours"
echo ""

echo "✨ RESULT:"
echo "   Your website will be live at:"
echo "   • https://yourdomain.com"
echo "   • https://www.yourdomain.com"
echo "   • FREE SSL certificate"
echo "   • Global CDN (fast worldwide)"
echo "   • Unlimited bandwidth"
echo ""

echo "🔧 AUTOMATED SETUP COMMANDS:"
echo "   Run these after buying domain:"
echo ""
echo "   # Replace 'yourdomain.com' with your actual domain"
echo "   echo 'yourdomain.com' > CNAME"
echo "   git add CNAME"
echo "   git commit -m 'Add custom domain'"
echo "   git push origin main"
echo ""
echo "==============================================="